name: documorph
description: "A multi-purpose document scanner and digital converter app built with Flutter."

publish_to: 'none'

version: 1.0.0+1

environment:
  sdk: '>=3.0.0 <4.0.0'

dependencies:
  flutter:
    sdk: flutter
  image_picker: ^1.1.2
  google_mlkit_text_recognition: ^0.14.0
  share_plus: ^10.0.0
  qr_flutter: ^4.1.0
  pdf: ^3.10.0
  printing: ^5.11.0

dev_dependencies:
  flutter_test:
    sdk: flutter
  flutter_lints: ^2.0.0

flutter:
  uses-material-design: true
